### ISSUE TITLE
can't install koa-minify

### ISSUE THREAD

**Issue by xueqingxiao** [coderaiser/koa-minify#1]
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.1.0/bin/node" "/usr/local/bin/npm" "install" "koa-minify" "--save"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! path /Users/shawn/Developer/git/wemart/wemart-mall/node_modules/koa-minify/bin/harmony.js koa-minify
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/shawn/Developer/git/wemart/wemart-mall/node_modules/koa-minify/bin/harmony.js koa-minify'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/shawn/Developer/git/wemart/wemart-mall/npm-debug.log

**Comment by coderaiser** [comment]
Fixed in [v1.0.9](https://github.com/coderaiser/koa-minify/releases/tag/v1.0.9).
Thank you.

**Comment by xueqingxiao** [comment]
Thanks @coderaiser

**Comment by xueqingxiao** [comment]
Thanks @coderaiser
